name: glest # you probably want to 'snapcraft register <name>'
# the base snap is the execution environment for this snap
version: '2.0' # just for humans, typically '1.2+git' or '1.3.2'
base: core18
summary: Glest # 79 char long summary
description: |
  Glest is a free real-time strategy game.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  glest:
    desktop: usr/share/applications/io.glest.Glest.desktop
    command: glest
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
    plugs:
      - network
      - network-bind
      - home
      - opengl
      - pulseaudio
      - x11

  glest.mapeditor:
    command: glest_editor

  glest.g3dviewer:
    command: glest_g3dviewer
      
parts:
  glest:
    plugin: cmake
    configflags:
      - "-DCMAKE_INSTALL_PREFIX=/usr"
    source-type: git
    source: https://github.com/glest/glest-source.git
    #source-type: local
    #source: glest-source
    build-packages:
      - build-essential
      - cmake
      - libsdl2-dev
      - libopenal-dev
      - liblua5.3-dev
      - libcurl4-dev
      - libjpeg-dev
      - libpng-dev
      - libfreetype6-dev
      - libwxgtk3.0-dev
      - libcppunit-dev
      - libfribidi-dev
      - libftgl-dev
      - libglew-dev
      - libogg-dev
      - libvorbis-dev
      - libminiupnpc-dev
      - libircclient-dev
      - libvlc-dev
      - libvlccore-dev
      - libxml2-dev
      - libx11-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev 
      - librtmp-dev
      - libkrb5-dev
      - libldap2-dev
      - libidn11-dev
      - libgnutls28-dev
      - libnghttp2-dev
      - libssh2-1-dev
      - libpsl-dev
    stage-packages:
      - famfamfam-flag-png
      - p7zip-full
      - libcurl4
      - libfontconfig1
      - libfribidi0
      - libftgl2
      - libgcc1
      - libgl1-mesa-glx
      - libgl1
      - libglew2.0
      - libglu1-mesa
      - libircclient1
      - libjpeg8
      - liblua5.3-0
      - libminiupnpc10
      - libopenal1
      - libpng16-16
      - libsdl2-2.0-0
      - libstdc++6
      - libvorbisfile3
      - libwxbase3.0-0v5
      - libwxgtk3.0-0v5
      - libx11-6
      - libpulse0
    override-build: |
      snapcraftctl build
      for f in $SNAPCRAFT_PART_INSTALL/usr/bin/7z*
      do
        sed -i 's/\/usr/$SNAP\/usr/' $f
      done
      
  glest-data:
    plugin: cmake
    configflags:
      - "-DCMAKE_INSTALL_PREFIX=/usr"
    #source-type: local
    #source: glest-data
    source-type: git
    source: https://github.com/glest/glest-data.git

    
